# Generated by GitHub Copilot on 2026-01-20

from django.db import migrations, models


def forwards(apps, schema_editor):
    UserProfile = apps.get_model('blog', 'UserProfile')

    # Qualquer coisa que não seja 'admin' vira 'author'
    UserProfile.objects.exclude(role='admin').update(role='author')


def backwards(apps, schema_editor):
    # Não dá pra recuperar a role antiga (editor/contributor)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile_address_userprofile_allowed_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Administrador'), ('author', 'Autor')],
                default='author',
                max_length=20,
                verbose_name='Função no Blog',
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
