# Generated by Django 5.2.10 on 2026-01-20 19:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0008_userprofile_facebook_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAuthor',
            fields=[
            ],
            options={
                'verbose_name': 'Autor pendente',
                'verbose_name_plural': 'Pendentes de aprovação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
