# Generated by Django 5.2.10 on 2026-01-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pendingauthor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=1000)),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkclicks', to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'post'], name='blog_linkcl_created_63127c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('post', 'Post'), ('home', 'Home'), ('category', 'Categoria'), ('author', 'Autor')], db_index=True, max_length=20)),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_pageviews', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to='blog.category')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'kind'], name='blog_pagevi_created_076c29_idx'), models.Index(fields=['post', 'created_at'], name='blog_pagevi_post_id_5cc3e7_idx')],
            },
        ),
    ]
