# Generated by Django 5.2.10 on 2026-01-20 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_linkclick_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ref_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pageview',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, help_text='direct | search | social | referral | utm', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('time', 'Tempo na página (segundos)'), ('scroll', 'Scroll máximo (%)')], db_index=True, max_length=20)),
                ('value_int', models.IntegerField(default=0)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'event'], name='blog_engage_created_2c51d3_idx'), models.Index(fields=['post', 'created_at'], name='blog_engage_post_id_363e43_idx')],
            },
        ),
    ]
