# Generated by Django 5.2.10 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_pageview_ref_domain_pageview_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável gerada automaticamente', null=True, unique=True),
        ),
    ]
