# Generated by Django 5.2.9 on 2026-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_image_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(help_text='Exemplo: ca-pub-1234567890123456. Você encontra isso no topo da página ao fazer login no Google AdSense.', max_length=100, verbose_name='ID do Publicador (Publisher ID)')),
                ('active', models.BooleanField(default=True, help_text='Desmarque para remover todos os anúncios do site temporariamente.', verbose_name='Ativar Anúncios')),
                ('in_article_slot_id', models.CharField(blank=True, help_text="Crie um bloco 'In-article' no AdSense e cole o 'data-ad-slot' aqui. Se vazio, o botão de anúncio não funcionará.", max_length=100, null=True, verbose_name='ID do Bloco: Dentro da Matéria')),
            ],
            options={
                'verbose_name': 'Configuração de Publicidade (AdSense)',
                'verbose_name_plural': 'Configuração de Publicidade (AdSense)',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image_crop_h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_crop_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_crop_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_crop_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_crop_h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_crop_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_crop_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_crop_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
